### ISSUE TITLE
Specify columns for the output table

### ISSUE THREAD

**Issue by wuqui** [tbanel/orgtbljoin#3]
Is it possible to specify which columns should be included in the joined table? I often don't want all of the columns from the reference table to be added to the master table.

The `:cols` parameter in your package `orgaggregate` allows one to specify which columns . I'm using this method to chain multiple table processing steps, but it's cumbersome. It would be ideal if this could be specified directly when joining.

**Comment by tbanel** [comment]
Hi Wuqui
Your request seems useful. I will investigate it.

**Comment by tbanel** [comment]
Done!
The new ```:cols``` parameter is available.
See _README_ for details.
Without ```:cols``` the behavior is the same.

**Comment by wuqui** [comment]
Brilliant! I just tried it, and it works perfectly, thank you! 🙂

**Comment by tbanel** [comment]
> Brilliant! I just tried it, and it works perfectly, thank you! slightly_smiling_face

You are welcome!
