### ISSUE TITLE
Feature request: support joining more than 2 tables

### ISSUE THREAD

**Issue by lhernanz** [tbanel/orgtbljoin#4]
Thanks for this very useful package! 

Would you be open to extend the package to join more than 2 tables? I have a number of small tables that I would love to be able to join by using this package. I am aware that you can use chaining, but that requires a lot of intermediate tables and far more code than needed. 

The idea would be that the `:ref-table` and the `:ref-column` parameters of the dynamic block could receive a list of elements (tables and column names), very similar to what it is possible with the `:cols` parameter.

Thanks!

**Comment by tbanel** [comment]
Hi [lhernanz](https://github.com/lhernanz)
This sounds like a natural extension.

In your use case, there is a single master table, and several reference tables, isn'it?
And the joining column in the master table is the same for all reference tables, is that true?

Let us think about this extension.

Sorry for my delayed answer. I was on the road those days.
Regards

**Comment by lhernanz** [comment]
Hi,

Yes, that would be the use case. A primary table and a number of secondary
tables to join. Therefore the joining column in the primary table is always
the same.

Thanks for thinking about this!

**Comment by tbanel** [comment]
Hi again Luis

I've just released the multi-refererence-tables version of `orgtbl-join`.
It is compatible with the previous single-reference-table version.

To specify several reference tables, just specify several times the `:ref-table`, `:mas-column`, `:ref-column`, and `:full` parameters.
Yes, the master column may be different for each reference table. Therefore in case it is the same for all tables, it must still be specified several times.

I close the issue.
Please feel free to re-open it if you find a bug, or if you want to further discuss the multi-table extension.

Allow a few hours for the package to appear on MELPA.
Or clone the project right now from GitHub.

Have fun!
Thierry

**Comment by lhernanz** [comment]
Hi, I could not test until now but it works as expected! Thanks for adding this!

**Comment by tbanel** [comment]
You are welcome
Your suggestion ended up in a nice new feature
Have fun!
