### ISSUE TITLE
Bug: incorrect RE while looking for tables

### ISSUE THREAD

**Issue by lhernanz** [tbanel/orgtbljoin#5]
Hi,
There is a small bug at: https://github.com/tbanel/orgtbljoin/blob/e133c1feb597a0d010f47a82ec5c869080fa7955/orgtbl-join.el#L207 

The regexp should include an additional caret to ensure that tables are matched only the the start of a line. With the current code, any pipe in the lines following the name (e.g. if there are more comment lines with more table metadata or invocation to dynamic methods), they will get matched and the table will not be found. Therefore, the right line should be:

```elisp
        (unless (and (re-search-forward "^\\(\\*+ \\)\\|^[ \t]*|" nil t)
```

**Comment by tbanel** [comment]
Thanks!
I will fix that and give you credit.

I'm currently working on your feature request: joining several tables. Good progress have been made. Stay tuned.

**Comment by tbanel** [comment]
Your fix have just been committed.
And there was a similar bug in [orgtbl-aggregate.el](https://github.com/tbanel/orgaggregate) also fixed.
Thanks!
